import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import AdminPanelLayout from "@/components/admin-panel-layout";
import { ScrollArea } from "@/components/ui/scroll-area";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body>
        <AdminPanelLayout>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ScrollArea className="h-screen overflow-auto w-full min-w-full">
              {children}
            </ScrollArea>
          </ThemeProvider>
        </AdminPanelLayout>
      </body>
    </html>
  );
}
